---
name: directory-sso-proxy
namespace: directory
scm: git@github.com:uktrade/directory-sso-proxy.git
environments:
  - environment: dev
    type: gds
    app: dit-staging/dev-directory/directory-sso-proxy-dev
    vars:
      - API: 'api'
    secrets: true
    run:
      - "true"
  - environment: staging
    type: gds
    app: dit-staging/staging-directory/directory-sso-proxy-staging
    vars:
      - DISABLE_COLLECTSTATIC: 1
    secrets: true
    run:
      - "true"
  - environment: prod
    type: gds
    app: dit-services/directory/directory-sso-proxy
    vars:
      - DISABLE_COLLECTSTATIC: 1
    secrets: true
    run:
      - "true"
