---
name: exred
namespace: exred
scm: git@github.com:uktrade/exred.git
environments:
  - environment: dev
    type: gds
    app: dit-staging/dev-exred/exred-dev
    secrets: false
    run:
      - "true"
  - environment: staging
    type: gds
    app: dit-staging/staging-exred/exred-staging
    secrets: false
    run:
      - "true"
